#!/bin/bash
# A small rofi / dmenu script
# Replace awesome with your WM
    
case "$(echo -e "Suspendre\nÉteindre\nRedémarrer" | rofi -dmenu \
	-p 'Quitter' -l 10 \
	"Status:" )" in
	Suspendre) swaylock -f --ignore-empty-password --image ~/stuff/pic/wallpapers/pattern.jpg && sleep 1 && systemctl suspend;;
        Éteindre) exec systemctl poweroff;;
        Redémarrer) exec systemctl reboot;;

esac
